### ISSUE TITLE
Archive other mailing lists?

### ISSUE THREAD

**Issue by krlmlr** [MichaelChirico/r-mailing-list-archive#3]
For example, R-sig-mac? Is the initial ingestion different from the regular update?

**Comment by MichaelChirico** [comment]
I believe you can add the entry and it will "just work", since each run downloads all previous postings _unless_ they're already found:

https://github.com/MichaelChirico/r-mailing-list-archive/blob/25bc1c3c5a0f5f051b5b01c1c85df2144b9eede5/update_archives.R#L27-L36

I think in the past I've run the script manually on initial inclusion to avoid waiting for the next GHA run to check if something's broken.

Happy to add more archives, in any case -- do you want to try out a PR?

**Comment by MichaelChirico** [comment]
Looks like it worked, thanks!

https://github.com/MichaelChirico/r-mailing-list-archive/tree/master/r-sig-mac

(funny that there's a Jan-1970 entry 😂)

**Comment by krlmlr** [comment]
Thanks! Will add more as we go.

Would it be too bad to scrape weekly or daily?

**Comment by MichaelChirico** [comment]
> Would it be too bad to scrape weekly or daily?

I think it should be fine. I do worry a bit about the repo size though. It's already at 1.4GiB. That's mostly thanks to `r-help` at 877MiB by itself, but there is a huge 280MiB file in the .git folder. I figure tracking changes for every new post will roughly 2x the storage needed for each file unless we're careful about merging so that only `+` changes are recorded.

OTOH, maybe that's all in the past:

```
file_size[
  source == "r-help",
  paste(round(sum(size)/1024/1024, 1), "MiB"),
  keyby = year
]
    year       V1
 1: 1997  0.9 MiB
 2: 1998  2.3 MiB
 3: 1999  4.5 MiB
 4: 2000  8.5 MiB
 5: 2001   14 MiB
 6: 2002 20.9 MiB
 7: 2003 24.5 MiB
 8: 2004 32.1 MiB
 9: 2005 38.6 MiB
10: 2006 65.4 MiB
11: 2007 48.5 MiB
12: 2008 61.6 MiB
13: 2009 73.1 MiB
14: 2010 77.7 MiB
15: 2011 74.1 MiB
16: 2012 88.4 MiB
17: 2013 48.5 MiB
18: 2014 36.7 MiB
19: 2015 39.3 MiB
20: 2016 27.6 MiB
21: 2017 23.9 MiB
22: 2018 27.2 MiB
23: 2019 17.3 MiB
24: 2020  7.7 MiB
25: 2021    5 MiB
26: 2022  5.4 MiB
27: 2023  3.1 MiB
    year       V1
```
